on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: CentOS 7
    runs-on: ubuntu-latest
    container: centos:7

    steps:
    - name: Install
      run: |
        yum install -y gcc gcc-c++ make python3 postgresql-server sudo

    - name: Install recent git yay
      run: |
        yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
        yum install -y git

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update DuckDB submodule
      run: |
        git config --global --add safe.directory /__w/duckdb-extensions-playground/duckdb-extensions-playground
        git submodule update --init --recursive 
        
    - name: Build
      run: |
        export PATH=/github/home/.local/bin:$PATH
        make release